version: '3'

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=queue

  producer:
    build:
      context: ./producer
    ports:
      - 8080:8080
    depends_on:
      - postgres

  consumer:
    build:
      context: ./consumer
    ports:
      - 8081:8080
    depends_on:
      - postgres